# Generated by Django 4.0.6 on 2022-07-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Арт'),
        ),
    ]
